/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Menu extends javax.swing.JFrame {
private int userID; // tambahkan variabel userID
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_checkhistory = new javax.swing.JToggleButton();
        btn_diagnosis = new javax.swing.JToggleButton();
        btn_resetpassword = new javax.swing.JToggleButton();
        btn_logout = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_checkhistory.setOpaque(false);
        btn_checkhistory.setContentAreaFilled(false);
        btn_checkhistory.setBorderPainted(false);
        btn_checkhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkhistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btn_checkhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 180, 50));

        btn_diagnosis.setOpaque(false);
        btn_diagnosis.setContentAreaFilled(false);
        btn_diagnosis.setBorderPainted(false);
        btn_diagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diagnosisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_diagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 275, 180, 50));

        btn_resetpassword.setOpaque(false);
        btn_resetpassword.setContentAreaFilled(false);
        btn_resetpassword.setBorderPainted(false);
        btn_resetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_resetpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 475, 190, 40));

        btn_logout.setOpaque(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setBorderPainted(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 575, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui componen/Menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_diagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diagnosisActionPerformed
        // Buka frame Diagnosis
    diagnosis diagnosisFrame = new diagnosis();
    diagnosisFrame.setVisible(true);

    // Tutup frame saat ini (opsional, tergantung pada kebutuhan)
    this.dispose();
    }//GEN-LAST:event_btn_diagnosisActionPerformed

    private void btn_checkhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkhistoryActionPerformed
        // Buka frame history
    history historyFrame = new history();
    historyFrame.setVisible(true);

    // Tutup frame saat ini (opsional, tergantung pada kebutuhan)
    this.dispose();
    }//GEN-LAST:event_btn_checkhistoryActionPerformed

    private void btn_resetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetpasswordActionPerformed
        // Buka frame ResetPassword
    ResetPassword resetPasswordFrame = new ResetPassword();
    resetPasswordFrame.setVisible(true);

    // Tutup frame saat ini (opsional, tergantung pada kebutuhan)
    this.dispose();
    }//GEN-LAST:event_btn_resetpasswordActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // Kembali ke frame Login (atau frame awal lainnya)
    Login loginFrame = new Login();
    loginFrame.setVisible(true);

    // Tutup frame saat ini (opsional, tergantung pada kebutuhan)
    this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
     public void setUserID(int userID) {
        this.userID = userID;
        // Anda dapat melakukan sesuatu dengan userID jika diperlukan
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_checkhistory;
    private javax.swing.JToggleButton btn_diagnosis;
    private javax.swing.JToggleButton btn_logout;
    private javax.swing.JToggleButton btn_resetpassword;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

  
}
