
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txUsername = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        txPassword = new javax.swing.JPasswordField();
        txConPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txUsername.setBackground(new java.awt.Color(197, 200, 205));
        txUsername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txUsername.setBorder(null);
        getContentPane().add(txUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 300, 40));

        txEmail.setBackground(new java.awt.Color(197, 200, 205));
        txEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txEmail.setBorder(null);
        getContentPane().add(txEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 300, 40));

        txPassword.setBackground(new java.awt.Color(197, 200, 205));
        txPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txPassword.setBorder(null);
        getContentPane().add(txPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 300, 40));

        txConPassword.setBackground(new java.awt.Color(197, 200, 205));
        txConPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txConPassword.setBorder(null);
        getContentPane().add(txConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 300, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui componen/Sign Up.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 220, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // Menampilkan pop-up berhasil mendaftar
    String username = txUsername.getText().toString().trim();
    String password = txPassword.getText().toString().trim();
    String email = txEmail.getText().toString().trim();
    String conpassword = txConPassword.getText().toString().trim();
    
    if (!password.equals(conpassword)){
        JOptionPane.showMessageDialog(null, "Password not match");
       }else if (password.equals("") || username.equals("")){
           JOptionPane.showMessageDialog(null,"Username or Password cannot be empty");
       }else{
           try {
               Connection c = Koneksi.getKoneksi();
               String sql = "INSERT INTO users (username, password, email) VALUES (?, ?, ?)";
               PreparedStatement p = c.prepareStatement(sql);
               p.setString(1, username);
               p.setString(2, password);
               p.setString(3, email);
               p.executeUpdate();
               p.close();
               JOptionPane.showMessageDialog(null, "Create Account Successfully");
               
           }catch(SQLException e){
               System.out.println("Error");
           }finally{
           this.dispose();
           Login a = new Login();
           a.setVisible(true);
       }
       }
    }//GEN-LAST:event_btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_simpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txConPassword;
    private javax.swing.JTextField txEmail;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
